print("Welcome to the tip calculator.")
total_bill = input("What was the total bill? $")
tip_value = input("What percentage tip would you like to give? 10, 12 or 15? ")
total_people = input("How many people to split the bill? ")
total_bill = float(total_bill)*(1+int(tip_value)/100)
each_pay = total_bill/float(total_people)
formato = "{:.2f}".format(each_pay)
print(f"Each person should pay: ${formato}")